name: bp_business_paraguana
description: "Business Paraguana App"
publish_to: 'none'
version: 2.1.2+7

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  firebase_messaging: ^15.0.0
  google_fonts: ^6.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
