name: business_paraguana
description: "App Premium Business Paraguaná"
publish_to: 'none'

# Esta versión marca el salto al diseño ejecutivo
version: 2.1.0+5

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # Librerías necesarias para el código Premium que pegaste:
  google_fonts: ^6.2.1
  animations: ^2.0.11
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Registro de tu logo para que no de error al abrir
  assets:
    - assets/logo.png
