name: Reparar y Construir APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: ğŸ›  Reparar Estructura
        run: |
          flutter create . --platforms=android --overwrite

      - name: ğŸ“¦ Instalar Dependencias
        run: flutter pub get

      - name: ğŸš€ Construir APK
        # El -t lib/main.dart asegura que use TU cÃ³digo
        run: flutter build apk --release --split-per-abi -t lib/main.dart
        
      - name: ğŸ“¤ Subir Archivo
        uses: actions/upload-artifact@v4
        with:
          name: MiApp-Instalable
          path: build/app/outputs/flutter-apk/*.apk
