name: Build Business Paraguana APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          # Eliminamos la línea de cache: gradle que causó el error anterior

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'

      - name: Generar Estructura y Firebase
        run: |
          # 1. Crear la estructura de Android que falta en el repo
          flutter create . --platforms android --project-name business_paraguana
          
          # 2. Configurar el motor de Firebase
          mkdir -p android/app
          cp google-services.json android/app/google-services.json
          
          # Inyectar las dependencias de Google en el archivo de construcción
          sed -i '/dependencies {/a \        classpath "com.google.gms:google-services:4.4.1"' android/build.gradle
          echo "apply plugin: 'com.google.gms.google-services'" >> android/app/build.gradle

      - name: Construir APK
        run: |
          flutter pub get
          flutter build apk --release --target=lib/app_principal.dart --no-tree-shake-icons

      - name: Subir APK Final
        uses: actions/upload-artifact@v4
        with:
          name: Business-Paraguana-VIP
          path: build/app/outputs/flutter-apk/app-release.apk
