name: Build Business Paraguana APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
          cache: true

      - name: Configurar Estructura Android
        run: |
          # Generamos la carpeta android de forma limpia
          flutter create . --platforms android --project-name business_paraguana
          
          # Movemos el archivo de la bóveda a su lugar real
          mkdir -p android/app
          cp google-services.json android/app/google-services.json
          
          # Configuramos el motor de Firebase en los archivos internos
          # Root build.gradle
          echo "buildscript { repositories { google(); mavenCentral() }; dependencies { classpath 'com.google.gms:google-services:4.4.1' } }" > android/build.gradle
          
          # App build.gradle
          echo "apply plugin: 'com.android.application'" > android/app/build.gradle
          echo "apply plugin: 'com.google.gms.google-services'" >> android/app/build.gradle

      - name: Construir Aplicación
        run: |
          flutter pub get
          flutter build apk --release --target=lib/app_principal.dart --no-tree-shake-icons

      - name: Entregar APK
        uses: actions/upload-artifact@v4
        with:
          name: Business-Paraguana-VIP
          path: build/app/outputs/flutter-apk/app-release.apk
